### ISSUE TITLE
the “train_data” came from a folder named "UCF-101_yuv_compress_str(opt.qp)_img"

### ISSUE THREAD

**Issue by CoolTony95** [Tongji-MIC-Lab/TDVC#1]
Dear Yi:
Thank you for your excellent work! I have encountered some confusion while trying to learn your paper, I would appreciate if you could give me some advice and guidance in your busy schedule.

I noticed that when I executed the script [train_cls.py] for training, the “train_data” came from a folder named "UCF-101_yuv_compress_str(opt.qp)_img". I am confused because in the format conversion script [00-04.py] in folder “preprocess”, the folder "UCF-101_yuv_compress_str(opt.qp)_img" and its files are not generated. So, I would like to ask you is: what file does “UCF-101_yuv_compres_str(opt.qp)_img” contain? where does it come from? and how do I find or generate it to run the script [train_cls.py]?

Thank you for your valuable time and I am look forward to your answers.

**Comment by xkyi1111** [comment]
Sorry for the ambiguity in the scripts. I have reorganized the code, please try again.

**Comment by xkyi1111** [comment]
Sorry for the ambiguity in the scripts. I have reorganized the code, please try again.
